import { test, expect, type Page } from '@playwright/test'

async function ready(page: Page) {
  await page.goto('/')
  await expect(page.locator('canvas')).toHaveAttribute('data-texture-ready', 'true', { timeout: 60000 })
  await expect(page.locator('.loading-screen')).toHaveCount(0)
  await expect(page.locator('canvas')).toHaveAttribute('data-animating', 'false')
}

test('Details preserves a custom camera and Find eases from idle then restores it', async ({ page }) => {
  await ready(page)
  const canvas = page.locator('canvas')
  await page.mouse.move(140, 130)
  await page.mouse.down()
  await page.mouse.move(240, 165, { steps: 3 })
  await page.mouse.up()
  await page.mouse.down({ button: 'right' })
  await page.mouse.move(240, 110, { steps: 3 })
  await page.mouse.up({ button: 'right' })
  await page.mouse.down({ button: 'middle' })
  await page.mouse.move(275, 135, { steps: 3 })
  await page.mouse.up({ button: 'middle' })
  await expect(canvas).toHaveAttribute('data-animating', 'false')
  const view = await canvas.evaluate(el => ({ ...el.dataset }))
  await page.getByRole('button', { name: 'Details', exact: true }).click()
  await expect(canvas).toHaveAttribute('data-animating', 'false')
  for (const key of ['zoom', 'rotation', 'viewPan', 'cameraQuaternion']) {
    expect(await canvas.evaluate((el, key) => el.dataset[key], key)).toBe(view[key])
  }
  await page.getByRole('button', { name: 'Assemble', exact: true }).click()
  await expect(canvas).toHaveAttribute('data-progress', '1.0000')
  await page.getByRole('searchbox').fill('Renesas')
  await page.locator('.component-trigger').click()
  // Capture rendered frames, including the first frame after an idle interval.
  await canvas.evaluate(el => {
    const samples: { zoom: number; focused: string }[] = []
    const observer = new MutationObserver(() => {
      samples.push({ zoom: Number(el.dataset.cameraZoom), focused: el.dataset.focusedPart ?? '' })
      el.setAttribute('data-motion-samples', JSON.stringify(samples.slice(-100)))
    })
    observer.observe(el, { attributes: true, attributeFilter: ['data-render-frame'] })
  })
  const startZoom = Number(await canvas.getAttribute('data-camera-zoom'))
  await page.waitForTimeout(700)
  await page.getByRole('button', { name: 'Find on board', exact: true }).click()
  await expect(canvas).toHaveAttribute('data-focused-part', 'ra4m1')
  await expect(canvas).toHaveAttribute('data-animating', 'false')
  const endZoom = Number(await canvas.getAttribute('data-camera-zoom'))
  const samples = JSON.parse((await canvas.getAttribute('data-motion-samples'))!) as { zoom: number; focused: string }[]
  expect(samples.some(s => s.focused === 'ra4m1' && s.zoom > startZoom + 0.1 && s.zoom < endZoom - 0.1)).toBe(true)
  await page.screenshot({ path: 'artifacts/camera-focus.png' })
  await page.getByRole('button', { name: 'Show all', exact: true }).click()
  await expect(canvas).toHaveAttribute('data-animating', 'false')
  await page.getByRole('button', { name: 'Close details' }).click()
  await expect(canvas).toHaveAttribute('data-animating', 'false')
  for (const key of ['zoom', 'rotation', 'viewPan', 'cameraQuaternion']) {
    expect(await canvas.evaluate((el, key) => el.dataset[key], key)).toBe(view[key])
  }
  await expect.poll(async () => Number(await canvas.getAttribute('data-camera-zoom'))).toBeCloseTo(Number(view.cameraZoom), 1)
})

test('touch orbit, pinch-pan, finger handoff and layout orientation remain consistent', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1, reducedMotion: 'reduce' })
  const page = await context.newPage()
  try {
    await ready(page)
    const canvas = page.locator('canvas')
    const orientation = await canvas.getAttribute('data-camera-quaternion')
    await page.screenshot({ path: 'artifacts/touch-initial-portrait.png' })
    const session = await context.newCDPSession(page)
    const touch = (id: number, x: number, y: number) => ({ id, x, y, radiusX: 3, radiusY: 3, force: 1 })
    const send = (type: string, touchPoints: ReturnType<typeof touch>[]) => session.send('Input.dispatchTouchEvent', { type, touchPoints })
    await send('touchStart', [touch(1, 140, 350)])
    await send('touchMove', [touch(1, 170, 365)])
    await send('touchEnd', [])
    await expect(canvas).not.toHaveAttribute('data-rotation', '0.000,0.000')
    await expect(canvas).toHaveAttribute('data-dragged-parts', '0')
    const orbit = await canvas.getAttribute('data-rotation')
    await send('touchStart', [touch(1, 130, 350)])
    await send('touchStart', [touch(1, 130, 350), touch(2, 240, 350)])
    await send('touchMove', [touch(1, 125, 385), touch(2, 305, 385)])
    await expect.poll(async () => Number(await canvas.getAttribute('data-zoom'))).toBeGreaterThan(1.5)
    await expect(canvas).not.toHaveAttribute('data-view-pan', '0.000,0.000,0.000')
    await expect(canvas).toHaveAttribute('data-rotation', orbit!)
    const pinchZoom = await canvas.getAttribute('data-zoom')
    // Release finger 2, keeping finger 1 on the glass.
    await send('touchEnd', [touch(2, 305, 385)])
    await send('touchMove', [touch(1, 165, 395)])
    await send('touchEnd', [])
    await expect(canvas).not.toHaveAttribute('data-rotation', orbit!)
    await expect(canvas).toHaveAttribute('data-zoom', pinchZoom!)
    await page.getByRole('button', { name: 'Details', exact: true }).tap()
    await expect(canvas).toHaveAttribute('data-camera-quaternion', orientation!)
    await page.getByRole('button', { name: 'Close details' }).tap()
    await expect(canvas).toHaveAttribute('data-camera-quaternion', orientation!)
    await page.screenshot({ path: 'artifacts/touch-portrait.png' })
    await page.setViewportSize({ width: 844, height: 390 })
    await expect(page.getByRole('group', { name: 'Touch controls' })).toBeVisible()
    await expect(canvas).toHaveAttribute('data-camera-quaternion', orientation!)
    await page.getByRole('button', { name: 'Details', exact: true }).tap()
    await expect(canvas).toHaveAttribute('data-camera-quaternion', orientation!)
    await page.getByRole('button', { name: 'Close details' }).tap()
    await page.screenshot({ path: 'artifacts/touch-landscape.png' })
    // A fresh landscape visit exposes the same controls and upright camera.
    await ready(page)
    await expect(canvas).toHaveAttribute('data-camera-quaternion', orientation!)
    await expect(page.getByRole('group', { name: 'Touch controls' })).toBeVisible()
    await page.getByRole('button', { name: 'Move parts', exact: true }).tap()
    await expect(page.getByRole('button', { name: 'Move parts', exact: true })).toHaveAttribute('aria-pressed', 'true')
    const THREE = await import('three')
    const rect = (await canvas.boundingBox())!
    const camera = new THREE.OrthographicCamera(-rect.width / 2, rect.width / 2, rect.height / 2, -rect.height / 2, .1, 100)
    camera.position.set(7.5, 11.8, 14); camera.lookAt(0, 1, 0)
    camera.zoom = Math.min(rect.width / 13.8, rect.height / 11.4); camera.updateProjectionMatrix(); camera.updateMatrixWorld()
    const point = new THREE.Vector3(2.8, 2.9, -2.05).project(camera)
    const x = rect.x + (point.x + 1) * rect.width / 2, y = rect.y + (1 - point.y) * rect.height / 2
    await send('touchStart', [touch(1, x, y)])
    await send('touchMove', [touch(1, x + 24, y - 18)])
    await send('touchEnd', [])
    await expect(canvas).toHaveAttribute('data-dragged-parts', '1')
    await send('touchStart', [touch(1, 90, 130)])
    await send('touchCancel', [])
    await page.getByRole('button', { name: 'Reset parts and view' }).tap()
    await expect(canvas).toHaveAttribute('data-rotation', '0.000,0.000')
    await expect(canvas).toHaveAttribute('data-zoom', '1.000')
  } finally { await context.close() }
})
