import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

async function enter(page: Page) {
  await page.goto('/')
  await expect(page.locator('canvas')).toHaveAttribute('data-texture-ready','true',{timeout:60000})
  await expect(page.locator('.loading-screen')).toHaveCount(0)
  await expect(page.locator('main')).not.toHaveAttribute('inert')
  await expect.poll(() => page.locator('.scene-area').evaluate(el => getComputedStyle(el).opacity)).toBe('1')
}

test('photo surfaces, scroll assembly and separate component inspector', async ({page}) => {
  test.setTimeout(240000)
  const errors: string[]=[]
  page.on('pageerror',error=>errors.push(error.message))
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text())})
  await enter(page)
  const canvas=page.locator('canvas')
  await expect(page.getByRole('heading')).toHaveCount(0)
  await expect(canvas).toHaveAttribute('data-part-count','25')
  await page.screenshot({path:'artifacts/v2-exploded.png'})
  await page.mouse.move(700,400)
  await page.mouse.wheel(0,5000)
  await expect(canvas).toHaveAttribute('data-progress','1.0000')
  await page.screenshot({path:'artifacts/v2-assembled.png'})
  await page.mouse.wheel(0,-5000)
  await expect(canvas).toHaveAttribute('data-progress','0.0000')
  await page.getByRole('button',{name:'Details',exact:true}).click()
  const panel=page.getByRole('complementary',{name:'Board details'})
  await expect(panel).toBeVisible()
  await expect.poll(async()=>{const a=(await canvas.boundingBox())!, b=(await panel.boundingBox())!;return Math.round(a.x+a.width)<=Math.round(b.x)}).toBe(true)
  await page.getByRole('searchbox',{name:'Search components'}).fill('Renesas')
  await page.locator('.component-trigger').click()
  await page.getByRole('button',{name:'Find on board',exact:true}).click()
  await expect(canvas).toHaveAttribute('data-focused-part','ra4m1')
  await expect(page.locator('.focus-caption')).toContainText('Renesas RA4M1')
  await expect.poll(async()=>Number(await canvas.getAttribute('data-zoom'))).toBeGreaterThan(1.5)
  await page.screenshot({path:'artifacts/v2-focus.png'})
  await page.getByRole('button',{name:'Show all',exact:true}).click()
  await expect(canvas).toHaveAttribute('data-focused-part','')
  await page.getByRole('slider',{name:'Assembly progress'}).focus()
  await page.keyboard.press('End')
  await expect(canvas).toHaveAttribute('data-progress','1.0000')
  await page.getByText('Camera controls',{exact:true}).click()
  await page.getByRole('button',{name:'View underside'}).click()
  await expect(canvas).toHaveAttribute('data-rotation',/^3\.14/)
  await page.getByRole('button',{name:'Close details'}).click()
  await page.screenshot({path:'artifacts/v2-underside.png'})
  expect(errors).toEqual([])
})

test('right-drag zoom is distinct from left-drag orbit; pan and reset work', async ({page}) => {
  await enter(page)
  const canvas=page.locator('canvas')
  await page.mouse.move(650,480)
  await page.mouse.down({button:'right'})
  await page.mouse.move(650,360,{steps:5})
  await page.mouse.up({button:'right'})
  await expect.poll(async()=>Number(await canvas.getAttribute('data-zoom'))).toBeGreaterThan(1.5)
  await expect(canvas).toHaveAttribute('data-rotation','0.000,0.000')
  await expect(canvas).toHaveAttribute('data-progress','0.0000')
  await page.getByRole('button',{name:'Reset parts and view'}).click()
  await expect(canvas).toHaveAttribute('data-zoom','1.000')
  await page.mouse.move(150,120)
  await page.mouse.down()
  await page.mouse.move(280,210,{steps:5})
  await page.mouse.up()
  await expect(canvas).not.toHaveAttribute('data-rotation','0.000,0.000')
  await page.mouse.move(400,300)
  await page.mouse.down({button:'middle'})
  await page.mouse.move(470,330,{steps:4})
  await page.mouse.up({button:'middle'})
  await expect(canvas).not.toHaveAttribute('data-pan','0.000,0.000,0.000')
  await page.getByRole('button',{name:'Reset parts and view'}).click()
  await expect(canvas).toHaveAttribute('data-rotation','0.000,0.000')
  await expect(canvas).toHaveAttribute('data-pan','0.000,0.000,0.000')
})

test('mobile inspector has its own space and usable text and keyboard controls', async ({page}) => {
  await page.setViewportSize({width:390,height:844})
  await page.emulateMedia({reducedMotion:'reduce'})
  await enter(page)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.getByRole('button',{name:'Show controls'}).click()
  await expect(page.getByRole('dialog',{name:'Controls'})).toContainText('Right-drag up / down')
  await page.keyboard.press('Escape')
  await page.getByRole('button',{name:'Details',exact:true}).click()
  const a=(await page.locator('canvas').boundingBox())!,b=(await page.locator('.inspector').boundingBox())!
  expect(a.y+a.height).toBeLessThanOrEqual(b.y+1)
  await page.getByRole('searchbox',{name:'Search components'}).fill('Renesas')
  await page.locator('.component-trigger').click()
  await page.getByRole('button',{name:'Find on board',exact:true}).click()
  await expect(page.locator('canvas')).toHaveAttribute('data-focused-part','ra4m1')
  await page.screenshot({path:'artifacts/v2-mobile-focus.png'})
  await page.getByRole('button',{name:'Assemble',exact:true}).click()
  await expect(page.locator('canvas')).toHaveAttribute('data-progress','1.0000')
  await expect(page.locator('canvas')).toHaveAttribute('data-focused-part','')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button',{name:'Details',exact:true})).toBeFocused()
  await page.screenshot({path:'artifacts/v2-mobile.png'})
})

test('model failure reveals readable component details',async ({page})=>{
  await page.route('**/*.glb',route=>route.abort())
  await page.goto('/')
  await expect(page.getByRole('complementary',{name:'Board details'})).toBeVisible()
  await expect(page.locator('.component-row')).not.toHaveCount(0)
  await expect(page.locator('.loading-screen')).toHaveCount(0)
})

test('a failed 3D script download keeps details and retry available', async ({page}) => {
  await page.route('**/assets/ArduinoScene-*.js', route => route.abort())
  await page.goto('/')
  await expect(page.getByRole('complementary',{name:'Board details'})).toBeVisible()
  await expect(page.getByRole('button',{name:'Try again'})).toBeVisible()
  await expect(page.locator('.loading-screen')).toHaveCount(0)
})

test('dragging a component preserves exact CAD assembly coordinates',async ({page})=>{
  await enter(page)
  const canvas=page.locator('canvas')
  const THREE=await import('three')
  const bounds=(await canvas.boundingBox())!
  const camera=new THREE.OrthographicCamera(-bounds.width/2,bounds.width/2,bounds.height/2,-bounds.height/2,.1,100)
  camera.position.set(7.5,11.8,14);camera.lookAt(0,1,0);camera.zoom=Math.min(bounds.width/13.8,bounds.height/11.4);camera.updateProjectionMatrix();camera.updateMatrixWorld()
  const point=new THREE.Vector3(2.8,2.9,-2.05).project(camera)
  const x=bounds.x+(point.x+1)*bounds.width/2,y=bounds.y+(1-point.y)*bounds.height/2
  await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+90,y-50,{steps:5});await page.mouse.up()
  await expect(canvas).toHaveAttribute('data-dragged-parts','1')
  await page.getByRole('button',{name:'Details',exact:true}).click()
  await page.getByRole('button',{name:'Assemble',exact:true}).click()
  await expect(canvas).toHaveAttribute('data-progress','1.0000')
  const {CAD_PARTS}=await import('../../src/data/cadParts')
  await expect(canvas).toHaveAttribute('data-selected-position',CAD_PARTS.find(p=>p.id==='ra4m1')!.assembled.map(v=>v.toFixed(3)).join(','))
})

test('production security policy, local fonts, idle rendering and accessible credits', async ({page}) => {
  const external: string[] = []
  const errors: string[] = []
  page.on('request', request => { if (/^https?:/.test(request.url()) && !request.url().startsWith('http://127.0.0.1:5174')) external.push(request.url()) })
  page.on('pageerror', error => errors.push(error.message))
  const response = await page.request.get('/')
  expect(response.headers()['content-security-policy']).toContain("script-src 'self' 'wasm-unsafe-eval'")
  expect(response.headers()['x-content-type-options']).toBe('nosniff')
  await enter(page)
  const canvas = page.locator('canvas')
  await expect.poll(async () => {
    const first = await canvas.getAttribute('data-render-frame')
    await page.waitForTimeout(400)
    return first === await canvas.getAttribute('data-render-frame')
  }).toBe(true)
  await page.getByRole('button', {name:'Details', exact:true}).click()
  await expect(page.getByRole('link', {name:'jose acuno dev'})).toBeVisible()
  await page.getByRole('link', {name:'jose acuno dev'}).scrollIntoViewIfNeeded()
  expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([])
  await page.screenshot({path:'artifacts/release-credits.png'})
  await page.getByRole('searchbox',{name:'Search components'}).fill('Renesas')
  await page.locator('.component-trigger').click()
  await page.getByRole('button',{name:'Find on board',exact:true}).click()
  await expect(canvas).toHaveAttribute('data-focused-part','ra4m1')
  expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([])
  expect(external).toEqual([])
  expect(errors).toEqual([])
})

test('real touch pinch, mobile assembly and landscape layout', async ({browser}) => {
  const context = await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2})
  const page = await context.newPage()
  try {
    await page.goto('http://127.0.0.1:5174/')
    await expect(page.locator('canvas')).toHaveAttribute('data-texture-ready','true',{timeout:60000})
    await expect(page.locator('.loading-screen')).toHaveCount(0)
    const session = await page.context().newCDPSession(page)
    const touch = (id: number, x: number, y: number) => ({id,x,y,radiusX:3,radiusY:3,force:1})
    await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(1,130,350)]})
    await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(1,130,350),touch(2,240,350)]})
    await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[touch(1,80,350),touch(2,290,350)]})
    await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})
    await expect.poll(async()=>Number(await page.locator('canvas').getAttribute('data-zoom'))).toBeGreaterThan(1.6)
    await page.getByRole('group',{name:'Touch controls'}).getByRole('button',{name:'Assemble',exact:true}).tap()
    await expect(page.locator('canvas')).toHaveAttribute('data-progress','1.0000')
    await page.getByRole('group',{name:'Touch controls'}).getByRole('button',{name:'Explode',exact:true}).tap()
    await expect(page.locator('canvas')).toHaveAttribute('data-progress','0.0000')
    await page.getByRole('button',{name:'Details',exact:true}).tap()
    expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([])
    await page.screenshot({path:'artifacts/release-mobile.png'})
    await page.setViewportSize({width:844,height:390})
    await expect.poll(async()=>{const a=(await page.locator('canvas').boundingBox())!,b=(await page.locator('.inspector').boundingBox())!;return a.x+a.width<=b.x+1}).toBe(true)
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
    await page.screenshot({path:'artifacts/release-landscape.png'})
  } finally { await context.close() }
})
