import { test, expect } from '@playwright/test'

test('official 3D model loads and assembly reverses through the page controls', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  const canvas = page.locator('canvas')
  await expect(canvas).toHaveAttribute('data-part-count', '25')
  await expect(canvas).toHaveAttribute('data-progress', '0.0000')
  await page.getByRole('button', { name: 'Bring it all together' }).click()
  await expect(page.getByRole('slider', { name: 'Assembly progress' })).toHaveValue('100')
  await expect(canvas).toHaveAttribute('data-progress', '1.0000')
  await page.getByRole('button', { name: 'Reset parts and view' }).click()
  await expect(canvas).toHaveAttribute('data-progress', '0.0000')
  const slider = page.getByRole('slider', { name: 'Assembly progress' })
  await slider.focus()
  await slider.press('End')
  await expect(slider).toHaveValue('100')
  await slider.press('Home')
  await expect(slider).toHaveValue('0')
  expect(errors).toEqual([])
})

test('components are inspectable without hovering and rotation resets', async ({ page }) => {
  await page.goto('/')
  const canvas = page.locator('canvas')
  await expect(canvas).toHaveAttribute('data-part-count', '25')
  await page.getByRole('button', { name: 'Rotate', exact: true }).click()
  const bounds = (await canvas.boundingBox())!
  await page.mouse.move(bounds.x + bounds.width * .55, bounds.y + bounds.height * .5)
  await page.mouse.down()
  await page.mouse.move(bounds.x + bounds.width * .75, bounds.y + bounds.height * .6, { steps: 12 })
  await page.mouse.up()
  await expect(canvas).not.toHaveAttribute('data-rotation', '0.000,0.000')
  await page.getByRole('button', { name: 'Reset parts and view' }).click()
  await expect(canvas).toHaveAttribute('data-rotation', '0.000,0.000')
  await page.getByRole('link', { name: 'The components' }).click()
  const component = page.locator('.component-row').first().getByRole('button').first()
  await component.click()
  await expect(component).toHaveAttribute('aria-expanded', 'true')
  await expect(page.getByRole('button', { name: 'Find on the board' })).toBeVisible()
  await page.getByRole('button', { name: 'Find on the board' }).click()
  await expect(canvas).toHaveAttribute('data-progress', '0.0000')
})

test('mobile and reduced-motion layouts preserve assembly and fit the viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.locator('canvas')).toHaveAttribute('data-part-count', '25')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Bring it all together' }).click()
  await expect(page.locator('canvas')).toHaveAttribute('data-progress', '1.0000')
  await page.getByRole('button', { name: 'Reset parts and view' }).click()
  await expect(page.locator('canvas')).toHaveAttribute('data-progress', '0.0000')
  await expect(page.getByRole('button', { name: 'Move parts' })).toBeVisible()
})
